# Generated by Django 4.1.2 on 2022-10-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="url",
            name="default_url",
            field=models.URLField(max_length=2555),
        ),
    ]
